### ISSUE TITLE
Mobile Banner Image not saving

### ISSUE THREAD

**Issue by Jimmyballantyne** [danrcoull/magento2-hero-banner-slider#2]
Hi,

On magento 2.3.5-p1 The desktop image saves fine but any image added as a mobile banner disappears on save?

Thanks for the nice module though!

**Comment by Jimmyballantyne** [comment]
Found the issue, the mobile save on the composer version doesn't add the images/banner prefix like in the github version. 

Fixed by adding it manually in the database.

**Comment by danrcoull** [comment]
Thanks for the report we are under development with this module allot more
aswell we have also implemented video possibilities into it aswell.

Though we are considering making it a small cost premium  download module.

**Comment by danrcoull** [comment]
Thanks for the donation if you would like the up to date module let me know
Happy to send you a zip via email if you want to try the new features.
